services:
  - type: web
    name: 1fi-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py seed_products && python manage.py collectstatic --no-input
    startCommand: gunicorn config.wsgi:application
    healthCheckPath: /api/products/
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: onefi-1-cj60.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: onefi